import { TranscriptCleaner, SpeakerEntry } from './types';

/**
 * Format 6: MacWhisper JSON
 *
 * Characteristics:
 * - JSON array of objects with "speaker" and "text" fields
 * - Generated by MacWhisper transcription app
 * - Speaker names may be real names, generic identifiers like "Speaker 1", or "Unknown"
 * - "Unknown" speakers are left as [Unknown] in the transcript and are never fed into
 *   the speaker resolution dialog. Each Unknown turn is kept separate (they may be
 *   different unidentified people).
 *
 * Example (real names):
 * [
 *   { "speaker": "Kevin Tronkowski", "text": "Hi. Okay." },
 *   { "speaker": "Shaji Mohammed", "text": "So there are three epics..." }
 * ]
 *
 * Example (generic identifiers):
 * [
 *   { "speaker": "Speaker 1", "text": "Hi. Okay." },
 *   { "speaker": "Speaker 2", "text": "So there are three epics..." }
 * ]
 *
 * Example (unknown speaker):
 * [
 *   { "speaker": "Unknown", "text": "Can everyone hear me?" }
 * ]
 */
export class MacWhisperJsonCleaner implements TranscriptCleaner {

	getName(): string {
		return 'MacWhisper JSON (Format 6)';
	}

	canHandle(content: string): boolean {
		const trimmed = content.trim();
		if (!trimmed.startsWith('[')) return false;
		try {
			const parsed = JSON.parse(trimmed);
			return (
				Array.isArray(parsed) &&
				parsed.length > 0 &&
				typeof parsed[0].speaker === 'string' &&
				typeof parsed[0].text === 'string'
			);
		} catch {
			return false;
		}
	}

	clean(content: string): string {
		const parsed: Array<{ speaker: string; text: string }> = JSON.parse(content.trim());

		// Consolidate consecutive entries by the same speaker.
		// "Unknown" entries are never consolidated — each is kept as its own block
		// since consecutive unknowns may be different unidentified people.
		const consolidated: SpeakerEntry[] = [];
		for (const item of parsed) {
			// Guard against entries missing speaker or text fields
			const speaker = (item.speaker ?? 'Unknown').trim();
			const text = (item.text ?? '').trim();
			if (!text) continue;

			const isUnknown = speaker.toLowerCase() === 'unknown';
			const last = consolidated[consolidated.length - 1];
			if (!isUnknown && last && last.speaker === speaker) {
				last.content += ' ' + text;
			} else {
				consolidated.push({ speaker, content: text });
			}
		}

		// Always use bracketed [Speaker Name] format — consistent with Google Recorder
		// and other vault conventions. For generic "Speaker N" identifiers this also
		// triggers the speaker resolution dialog.
		return this.formatEntries(consolidated);
	}

	private formatEntries(entries: SpeakerEntry[]): string {
		return entries
			.map(e => `[${e.speaker}]\n${e.content}`)
			.join('\n\n');
	}
}
