import { App, TFile } from 'obsidian';
import { MeetingProcessorSettings } from '../ui/settings-tab';
import { CopilotClientManager } from '../copilot-client';
import { SkillLoader } from '../skill-loader';
import { TranscriptDetector } from '../transcript';
import { PeopleManager } from '../people-manager';
import { StatusBarManager } from '../ui/status-bar';
import { SpeakerAttributionModal } from '../ui/speaker-attribution-modal';
import {
	extractSpeakerProfiles,
	extractAttendeeLinks,
	autoDetectMappings,
	rewriteTranscript,
	extractTranscriptText
} from '../speaker-resolver';
import * as mammoth from 'mammoth';
import { readFile } from 'fs/promises';
import { homedir } from 'os';

/**
 * Handles processing of general (non-standup) meetings
 */
export class GeneralMeetingHandler {
	private app: App;
	private settings: MeetingProcessorSettings;
	private copilotClient: CopilotClientManager;
	private skillLoader: SkillLoader;
	private transcriptDetector: TranscriptDetector;
	private peopleManager: PeopleManager;
	private statusBar: StatusBarManager;

	constructor(app: App, settings: MeetingProcessorSettings, copilotClient: CopilotClientManager, skillLoader: SkillLoader, statusBar: StatusBarManager) {
		this.app = app;
		this.settings = settings;
		this.copilotClient = copilotClient;
		this.skillLoader = skillLoader;
		this.transcriptDetector = new TranscriptDetector();
		this.peopleManager = new PeopleManager(app);
		this.statusBar = statusBar;
	}

	/**
	 * Process a general meeting file
	 */
	async process(file: TFile): Promise<void> {
		console.log('Processing general meeting:', file.basename);

		try {
			// Read the meeting content
			const content = await this.app.vault.read(file);

			// Check if already has Copilot Summary (skip transcript cleaning if so)
			const hasCopilotSummary = this.hasCopilotSummary(content);

			// 1. Extract/populate attendees
			this.statusBar.show('Extracting attendees...', 0);
			await this.processAttendees(file, content);

			// 2. Always expand any ![[...]] embed in # Transcript to inline text
			this.statusBar.show('Expanding transcript...', 0);
			await this.expandTranscriptEmbed(file);

			// 3. Resolve speaker labels ([Speaker N] → real attendee names)
			this.statusBar.show('Identifying speakers...', 0);
			await this.resolveSpeakers(file);

			// 4. Clean transcript (if enabled, no Copilot Summary, and setting enabled)
			if (!hasCopilotSummary && this.settings.autoCleanTranscript) {
				this.statusBar.show('Cleaning transcript...', 0);
				await this.cleanTranscript(file);
			}

			// 5. Generate summary
			this.statusBar.show('Generating summary...', 0);
			await this.generateSummary(file);

			this.statusBar.show('Complete!', 2000);
			console.log('General meeting processing complete');
		} catch (error) {
			this.statusBar.show('Error processing meeting', 3000);
			throw error;
		}
	}

	/**
	 * Check if meeting has a Copilot Summary section with meaningful content.
	 * Disclaimer-only sections (Teams AI boilerplate) are treated as empty.
	 */
	private hasCopilotSummary(content: string): boolean {
		const summaryMatch = content.match(/# Copilot Summary\s*\n([\s\S]*?)(?=\n#|$)/);
		if (!summaryMatch) return false;

		let summaryContent = summaryMatch[1].trim();
		if (!summaryContent || summaryContent.startsWith('#')) return false;

		// Strip Teams AI disclaimer boilerplate before checking for real content
		const disclaimerPatterns = [
			/AI-generated content.*?may be incorrect.*?\[Learn more\]\([^)]+\)/gi,
			/AI-generated content.*?may not be accurate.*?\[Learn more\]\([^)]+\)/gi,
			/This summary was generated by AI.*?may be incorrect.*?\[Learn more\]\([^)]+\]/gi,
			/\[Learn more\]\([^)]+\)/gi,
		];
		for (const pattern of disclaimerPatterns) {
			summaryContent = summaryContent.replace(pattern, '').trim();
		}

		return summaryContent.length >= 50;
	}

	/**
	 * Expand any ![[file.txt]] embed in the # Transcript section to inline text.
	 * Runs unconditionally so the transcript is always readable in the note.
	 */
	private async expandTranscriptEmbed(file: TFile): Promise<void> {
		const content = await this.app.vault.read(file);
		const rawTranscript = extractTranscriptText(content);

		if (!rawTranscript) {
			console.log('[expandTranscriptEmbed] No transcript section found');
			return;
		}

		const isEmbed = rawTranscript.length < 300 && (
			rawTranscript.includes('![[') ||
			rawTranscript.includes('.txt') ||
			rawTranscript.includes('.docx')
		);

		if (!isEmbed) {
			console.log('[expandTranscriptEmbed] Transcript is already inline text, skipping');
			return;
		}

		console.log('[expandTranscriptEmbed] Expanding embed:', rawTranscript.trim());
		const resolved = await this.resolveTranscriptContent(rawTranscript);
		if (!resolved || resolved.length < 20) {
			console.warn('[expandTranscriptEmbed] Could not resolve embed content, leaving as-is');
			return;
		}

		const updated = content.replace(
			/# Transcript\s*\n[\s\S]*?(?=\n# [^#]|$)/,
			`# Transcript\n\n${resolved}\n\n`
		);

		if (updated !== content) {
			await this.app.vault.modify(file, updated);
			console.log(`[expandTranscriptEmbed] Expanded embed to ${resolved.length} chars of inline text`);
		}
	}

	/**
	 * Resolve [Speaker N] labels in the transcript to real attendee names.
	 * Auto-detects confident mappings; shows a dialog for the rest.
	 */
	private async resolveSpeakers(file: TFile): Promise<void> {
		console.log('[resolveSpeakers] Starting...');

		const content = await this.app.vault.read(file);
		const rawTranscript = extractTranscriptText(content);

		console.log('[resolveSpeakers] Raw transcript section length:', rawTranscript.length, '— preview:', rawTranscript.substring(0, 80));

		if (!rawTranscript) {
			console.log('[resolveSpeakers] No transcript section found, skipping');
			return;
		}

		// Resolve embedded file references to actual text
		const transcriptText = await this.resolveTranscriptContent(rawTranscript);
		if (!transcriptText) {
			console.warn('[resolveSpeakers] Could not resolve transcript content, skipping');
			return;
		}

		console.log('[resolveSpeakers] Resolved transcript length:', transcriptText.length);

		// Nothing to do if there are no generic speaker labels
		if (!/\[Speaker \d+\]/i.test(transcriptText)) {
			console.log('[resolveSpeakers] No [Speaker N] labels found in transcript, skipping');
			return;
		}

		const attendees = extractAttendeeLinks(content);
		console.log('[resolveSpeakers] Attendees found:', attendees.map(a => a.displayName));

		if (attendees.length === 0) {
			console.log('[resolveSpeakers] No attendees found, skipping');
			return;
		}

		const profiles = extractSpeakerProfiles(transcriptText);
		console.log('[resolveSpeakers] Speaker profiles extracted:', profiles.map(p => `${p.speakerId}(${p.lineCount} lines)`));

		if (profiles.length === 0) {
			console.log('[resolveSpeakers] No speaker profiles extracted, skipping');
			return;
		}

		// Auto-detect high-confidence mappings
		const autoMappings = autoDetectMappings(profiles, attendees);
		const resolvedIds = new Set(autoMappings.map(m => m.speakerId));
		const unresolvedProfiles = profiles.filter(p => !resolvedIds.has(p.speakerId));

		console.log('[resolveSpeakers] Auto-detected mappings:', autoMappings.map(m => `${m.speakerId} → ${m.attendeeName} (${Math.round(m.confidence * 100)}%)`));
		console.log('[resolveSpeakers] Unresolved speakers:', unresolvedProfiles.map(p => p.speakerId));

		// Always show dialog so user can review auto-detections and assign unresolved speakers
		console.log('[resolveSpeakers] Opening SpeakerAttributionModal...');
		const finalMappings = await new Promise<typeof autoMappings>((resolve) => {
			new SpeakerAttributionModal(
				this.app,
				unresolvedProfiles,
				autoMappings,
				attendees,
				resolve
			).open();
		});

		console.log('[resolveSpeakers] Modal closed, final mappings:', finalMappings.map(m => `${m.speakerId} → ${m.attendeeName}`));

		if (finalMappings.length === 0) {
			console.log('[resolveSpeakers] No mappings to apply');
			return;
		}

		// Rewrite: if transcript was an embed, expand it inline with speaker names replaced.
		// If it was already inline, just replace in-place.
		const isEmbed = rawTranscript.includes('![[') || (rawTranscript.length < 300 && rawTranscript.includes('.txt'));
		let rewrittenTranscript = transcriptText;
		for (const mapping of finalMappings) {
			const pattern = new RegExp(`\\[${mapping.speakerId.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\]`, 'g');
			rewrittenTranscript = rewrittenTranscript.replace(pattern, `[${mapping.attendeeName}]`);
		}

		let updatedContent: string;
		if (isEmbed) {
			// Replace the entire # Transcript section, substituting the embed with inline text
			updatedContent = content.replace(
				/# Transcript\s*\n[\s\S]*?(?=\n# [^#]|$)/,
				`# Transcript\n\n${rewrittenTranscript}\n\n`
			);
			console.log('[resolveSpeakers] Expanded embed to inline transcript with speaker names');
		} else {
			updatedContent = rewriteTranscript(content, finalMappings);
		}

		if (updatedContent !== content) {
			await this.app.vault.modify(file, updatedContent);
			console.log(`[resolveSpeakers] Applied ${finalMappings.length} speaker mappings to transcript`);
		} else {
			console.log('[resolveSpeakers] No changes made (content unchanged)');
		}
	}

	/**
	 * Extract attendees from screenshots or content
	 */
	private async processAttendees(file: TFile, content: string): Promise<void> {
		console.log('Processing attendees...');
		
		// Only search for screenshots within the Attendees section
		const attendeesSectionMatch = content.match(/^# Attendees\n([\s\S]*?)(?=^# |\Z)/m);
		const attendeesContent = attendeesSectionMatch ? attendeesSectionMatch[1] : '';

		// Check for screenshot references in Attendees section only
		const screenshotPattern = /!\[\[(SCR-[^\]]+\.png)\]\]/g;
		const screenshots: string[] = [];
		let match;
		
		while ((match = screenshotPattern.exec(attendeesContent)) !== null) {
			screenshots.push(match[1]);
		}

		let extractedNames: string[] = [];

		// Try screenshots first if available
		if (screenshots.length > 0) {
			console.log(`Found ${screenshots.length} screenshots for attendee extraction`);
			extractedNames = await this.extractFromScreenshots(file, screenshots);
		}
		
		// Fall back to content extraction if screenshots didn't work
		if (extractedNames.length === 0) {
			console.log('Falling back to content extraction');
			extractedNames = await this.extractFromContent(content);
		}

		if (extractedNames.length > 0) {
			console.log(`Extracted ${extractedNames.length} attendees:`, extractedNames);
			await this.updateAttendeesSection(file, extractedNames);
		} else {
			console.log('No attendees extracted');
		}
	}

	/**
	 * Extract attendees from screenshot images using Copilot vision
	 */
	private async extractFromScreenshots(file: TFile, screenshots: string[]): Promise<string[]> {
		console.log('Extracting attendees from screenshots using vision...');
		
		const allNames: Set<string> = new Set();
		let visionFailed = false;
		
		for (const screenshot of screenshots) {
			try {
				// Get the image file from the vault
				const imagePath = this.app.metadataCache.getFirstLinkpathDest(screenshot, file.path);
				if (!imagePath) {
					console.warn(`Screenshot not found: ${screenshot}`);
					continue;
				}

				console.log(`Processing screenshot: ${screenshot}`);
				
				// Get the full filesystem path to the image
				const adapter = this.app.vault.adapter;
				const fullPath = (adapter as any).getFullPath(imagePath.path);
				console.log('Full image path:', fullPath);

				const prompt = `Extract all participant names from this Microsoft Teams meeting screenshot. Output ONLY a comma-separated list of full names like: "First Last, First Last". No other text or explanation.`;

				// Use CLI directly for vision analysis
				console.log('Using Copilot CLI directly for vision analysis...');
				const response = await this.copilotClient.analyzeImageWithCLI(fullPath, prompt);
				console.log('Vision response:', response);
				
				// Check if vision actually worked
				if (response.includes("don't see") || response.includes("cannot see") || 
				    response.includes("no image") || response.includes("Please provide") ||
				    response.includes("error") || response.length === 0) {
					console.warn('Vision analysis failed, will fall back to content extraction');
					visionFailed = true;
					break;
				}
				
				// Parse the response - extract just the names part if there's extra text
				let namesList = response.trim();
				
				// If response contains multiple lines, try to find the line with names
				if (namesList.includes('\n')) {
					const lines = namesList.split('\n').map(l => l.trim()).filter(l => l.length > 0);
					// Look for a line that looks like comma-separated names
					const namesLine = lines.find(l => l.includes(',') && !l.includes(':') && l.split(',').length > 1);
					if (namesLine) {
						namesList = namesLine;
					}
				}
				
				// Parse the names
				if (namesList && namesList !== 'NO_NAMES_FOUND') {
					const names = namesList.split(',').map(n => n.trim()).filter(n => 
						n.length > 0 && 
						n.length < 60 &&
						!/don't|cannot|please/i.test(n) &&  // Filter out error messages
						/^[A-Za-z]/.test(n) &&              // Must start with a letter
						!/[\/\(\)\+\[\]]/.test(n) &&        // No special chars typical of non-names
						n.split(' ').length >= 2             // Must have at least first and last name
					);
					names.forEach(name => allNames.add(name));
					console.log(`Extracted ${names.length} names from ${screenshot}:`, names);
				}
				
			} catch (error) {
				console.error(`Error processing screenshot ${screenshot}:`, error);
				visionFailed = true;
			}
		}
		
		// If vision failed, try content extraction as fallback
		if (visionFailed || allNames.size === 0) {
			console.log('Vision extraction failed or returned no names, falling back to content extraction');
			return [];  // Return empty so caller can try content extraction
		}
		
		return Array.from(allNames);
	}

	/**
	 * Extract attendees from meeting content (fallback method)
	 */
	private async extractFromContent(content: string): Promise<string[]> {
		console.log('Extracting attendees from content (fallback - limited capability)...');
		
		// Look for speaker patterns in transcript: [Speaker Name] or **Speaker Name:**
		const speakers = new Set<string>();
		const jiraKeyPattern = /^[A-Z]+-\d+$/; // Match JIRA keys like GLCP-12345
		const speakerNumberPattern = /^Speaker \d+$/i; // Match "Speaker 1", "Speaker 2", etc. (case insensitive)
		const fileExtPattern = /\.(docx?|pdf|xlsx?|pptx?|txt|md)$/i; // Match file extensions
		
		// Pattern 1: [Speaker Name] format (but not image references or JIRA keys)
		const bracketPattern = /\[([^\]]+)\]/g;
		let match;
		
		while ((match = bracketPattern.exec(content)) !== null) {
			const speaker = match[1].trim();
			// Skip image references, JIRA keys, generic speakers, files, and other non-names
			if (!speaker.includes('.png') &&          // Skip image filenames
			    !speaker.includes('.jpg') &&          // Skip image filenames
			    !fileExtPattern.test(speaker) &&      // Skip Word docs, PDFs, etc.
			    !speaker.includes('/') &&             // Skip paths like "People/Name"
			    speaker.length > 3 &&                 // Reasonable name length
			    speaker.length < 50 &&                // Not too long
			    /[a-zA-Z]/.test(speaker) &&           // Contains letters
			    !jiraKeyPattern.test(speaker) &&      // Not a JIRA key
			    !speakerNumberPattern.test(speaker) && // Not "Speaker 1", etc.
			    speaker !== 'Learn more') {           // Not "Learn more" link
				speakers.add(speaker);
			}
		}
		
		// Pattern 2: **Name:** format (common in some transcripts)
		const boldPattern = /\*\*([^*:]+):\*\*/g;
		while ((match = boldPattern.exec(content)) !== null) {
			const speaker = match[1].trim();
			if (speaker.length > 3 && 
			    speaker.length < 50 && 
			    !speakerNumberPattern.test(speaker) &&
			    !jiraKeyPattern.test(speaker)) {
				speakers.add(speaker);
			}
		}
		
		// Deduplicate: Remove plain names if wiki-link format exists
		// e.g., keep "[Tronkowski, Kevin|Kevin Tronkowski" and remove "Kevin Tronkowski"
		const speakersArray = Array.from(speakers);
		const filtered = speakersArray.filter(name => {
			// If this is a plain name, check if a wiki-link version exists
			if (!name.includes('|')) {
				// Check if any other entry contains this name in wiki-link format
				const hasWikiVersion = speakersArray.some(other => 
					other.includes('|') && other.includes(name)
				);
				return !hasWikiVersion; // Keep only if no wiki version exists
			}
			return true; // Always keep wiki-link format
		});
		
		console.log(`Found ${filtered.length} unique attendees (after deduplication):`, filtered);
		
		// If we only found generic speakers, warn the user
		const allGeneric = filtered.every(s => speakerNumberPattern.test(s));
		if (allGeneric && filtered.length > 0) {
			console.warn('Only generic speaker labels found (Speaker 1, Speaker 2, etc.). Vision API would provide real names from screenshots.');
		}
		
		return filtered;
	}

	/**
	 * Update the Attendees section with extracted names
	 * Creates People profiles and generates links
	 */
	private async updateAttendeesSection(file: TFile, names: string[]): Promise<void> {
		console.log('Updating Attendees section...');
		
		const content = await this.app.vault.read(file);
		
		// Get or create profiles for each attendee (respecting setting)
		const profiles = await Promise.all(
			names.map(async name => {
				if (this.settings.autoCreateProfiles) {
					return await this.peopleManager.getOrCreateProfile(name);
				} else {
					// Just find existing profiles, don't create
					return await this.peopleManager.findProfile(name);
				}
			})
		);
		
		// Build the attendees list with links
		const attendeesList = profiles.map(profile => {
			if (profile.exists) {
				const link = this.peopleManager.generateLink(profile);
				return `- ${link}`;
			} else {
				// No profile and auto-create disabled, just use plain name
				return `- ${profile.displayName}`;
			}
		}).join('\n');
		
		const attendeesContent = `\n## In Meeting (${names.length})\n${attendeesList}\n`;
		
		// Find and update the Attendees section
		const attendeesRegex = /# Attendees\s*\n([\s\S]*?)(?=\n+#\s)/;
		let newContent: string;
		
		if (attendeesRegex.test(content)) {
			// Replace existing content
			newContent = content.replace(attendeesRegex, `# Attendees${attendeesContent}\n`);
		} else {
			// Couldn't find section (shouldn't happen)
			console.warn('Attendees section not found in file');
			return;
		}
		
		await this.app.vault.modify(file, newContent);
		console.log('Attendees section updated');
	}

	/**
	 * Convert ArrayBuffer to base64 string
	 */
	private arrayBufferToBase64(buffer: ArrayBuffer): string {
		let binary = '';
		const bytes = new Uint8Array(buffer);
		const len = bytes.byteLength;
		for (let i = 0; i < len; i++) {
			binary += String.fromCharCode(bytes[i]);
		}
		return btoa(binary);
	}

	/**
	 * Clean transcript based on detected format
	 */
	private async cleanTranscript(file: TFile): Promise<void> {
		console.log('[cleanTranscript] Starting...');
		
		const content = await this.app.vault.read(file);
		
		// Extract transcript section
		const transcriptMatch = content.match(/# Transcript\s*\n([\s\S]*?)(?=\n#|$)/);
		if (!transcriptMatch) {
			console.log('[cleanTranscript] No transcript section found');
			return;
		}

		const rawTranscript = transcriptMatch[1].trim();
		if (!rawTranscript || rawTranscript.length < 10) {
			console.log('[cleanTranscript] Transcript section is empty or too short');
			return;
		}

		console.log('[cleanTranscript] Raw transcript length:', rawTranscript.length, '— preview:', rawTranscript.substring(0, 80));

		// Resolve any embedded file reference to actual text
		const resolvedText = await this.resolveTranscriptContent(rawTranscript);
		if (!resolvedText) {
			console.warn('[cleanTranscript] Could not resolve transcript content, skipping clean');
			return;
		}

		console.log('[cleanTranscript] Resolved transcript length:', resolvedText.length);

		// Detect format and clean
		const result = this.transcriptDetector.detectAndClean(resolvedText);
		console.log(`[cleanTranscript] Cleaned using: ${result.cleaner}, output length: ${result.cleaned.length}`);

		if (!result.cleaned || result.cleaned.length < 10) {
			console.warn('[cleanTranscript] Cleaner produced empty output, skipping write to avoid data loss');
			return;
		}

		// Replace transcript section (embed reference is replaced with inline cleaned text)
		const newContent = content.replace(
			/# Transcript\s*\n[\s\S]*?(?=\n# [^#]|$)/,
			`# Transcript\n\n${result.cleaned}\n\n`
		);

		await this.app.vault.modify(file, newContent);
		console.log('[cleanTranscript] Transcript cleaned and saved');
	}

	/**
	 * Resolve a raw transcript value to actual text.
	 * If rawTranscript is an embedded file reference (![[filename.txt]]), reads and returns the file text.
	 * Otherwise returns rawTranscript unchanged (already inline text).
	 * Returns null if resolution fails.
	 */
	private async resolveTranscriptContent(rawTranscript: string): Promise<string | null> {
		const isEmbedRef = rawTranscript.length < 300 && (
			rawTranscript.includes('.docx') ||
			rawTranscript.includes('.doc') ||
			rawTranscript.includes('.txt') ||
			rawTranscript.includes('![[')
		);

		if (!isEmbedRef) {
			console.log('[resolveTranscriptContent] Already inline text, length:', rawTranscript.length);
			return rawTranscript;
		}

		console.log('[resolveTranscriptContent] Detected embed/file reference:', rawTranscript.substring(0, 80));

		try {
			let filename = rawTranscript;
			filename = filename.replace(/!?\[\[/g, '').replace(/\]\]/g, '').trim();
			console.log('[resolveTranscriptContent] Extracted filename:', filename);

			const isAbsolutePath = filename.startsWith('/');
			const isHomePath = filename.startsWith('~');
			const isTxtFile = filename.toLowerCase().endsWith('.txt');
			const isDocxFile = filename.toLowerCase().endsWith('.docx') || filename.toLowerCase().endsWith('.doc');

			if (!isTxtFile && !isDocxFile) {
				console.warn('[resolveTranscriptContent] Unsupported file type:', filename);
				return null;
			}

			if (isAbsolutePath || isHomePath) {
				const fullPath = isHomePath ? filename.replace(/^~/, homedir()) : filename;
				console.log('[resolveTranscriptContent] Reading external file:', fullPath);
				if (isTxtFile) {
					const text = await readFile(fullPath, 'utf-8');
					console.log('[resolveTranscriptContent] Read external .txt, length:', text.length);
					return text;
				} else {
					const buffer = await readFile(fullPath);
					const result = await mammoth.extractRawText({ buffer });
					console.log('[resolveTranscriptContent] Extracted docx text, length:', result.value.length);
					return result.value;
				}
			} else {
				const possiblePaths = [
					filename,
					`Media/${filename}`,
					`Attachments/${filename}`,
					`Files/${filename}`
				];
				console.log('[resolveTranscriptContent] Searching vault paths:', possiblePaths);

				let docFile: TFile | null = null;
				for (const path of possiblePaths) {
					const f = this.app.vault.getAbstractFileByPath(path);
					if (f instanceof TFile) {
						docFile = f;
						console.log('[resolveTranscriptContent] Found vault file at:', path);
						break;
					}
				}

				if (!docFile) {
					console.warn('[resolveTranscriptContent] File not found in vault:', filename);
					return null;
				}

				if (isTxtFile) {
					const text = await this.app.vault.read(docFile);
					console.log('[resolveTranscriptContent] Read vault .txt, length:', text.length);
					return text;
				} else {
					const arrayBuffer = await this.app.vault.readBinary(docFile);
					const buffer = Buffer.from(arrayBuffer);
					const result = await mammoth.extractRawText({ buffer });
					console.log('[resolveTranscriptContent] Extracted vault docx text, length:', result.value.length);
					return result.value;
				}
			}
		} catch (error) {
			console.error('[resolveTranscriptContent] Error resolving transcript file:', error);
			return null;
		}
	}

	/**
	 * Check if Unified Summary already exists with content
	 */
	private hasUnifiedSummary(content: string): boolean {
		const match = content.match(/# Unified Summary\s*\n([\s\S]*?)(?=\n#|$)/);
		return match !== null && match[1].trim().length > 20;
	}

	/**
	 * Check if Transcript section exists with content
	 */
	private hasTranscript(content: string): boolean {
		const match = content.match(/# Transcript\s*\n([\s\S]*?)(?=\n#|$)/);
		return match !== null && match[1].trim().length > 20;
	}

	/**
	 * Main summary generation - routes to standard or enhanced workflow
	 */
	private async generateSummary(file: TFile): Promise<void> {
		console.log('Generating general meeting summary...');
		
		const content = await this.app.vault.read(file);
		
		// Check what sources we have
		const hasCopilotSummary = this.hasCopilotSummary(content);
		const hasTranscript = this.hasTranscript(content);

		if (hasCopilotSummary && hasTranscript) {
			// Both available: generate Transcript Summary + Unified Summary
			console.log('Both Copilot Summary and transcript available - using enhanced workflow');
			await this.generateEnhancedSummary(file, content);
		} else if (!hasCopilotSummary && hasTranscript) {
			// Transcript only: generate Transcript Summary, no Unified Summary
			console.log('Transcript only - generating Transcript Summary');
			await this.generateStandardSummary(file, content);
		} else {
			// No transcript to process
			console.log('No transcript available, skipping summary generation');
		}
	}

	/**
	 * Transcript-only summary workflow — writes to # Transcript Summary section
	 */
	private async generateStandardSummary(file: TFile, content: string): Promise<void> {
		console.log('Generating transcript summary...');
		
		// Get the summary generation skill
		const summarySkill = this.skillLoader.getSkill('summary-generation');
		if (!summarySkill) {
			console.warn('Summary generation skill not found');
			return;
		}

		// Use transcript content only
		const transcriptMatch = content.match(/# Transcript\s*\n([\s\S]*?)(?=\n#|$)/);
		const contentToSummarize = transcriptMatch?.[1]?.trim() ?? '';

		if (!contentToSummarize || contentToSummarize.length < 20) {
			console.log('No transcript content available for summary generation');
			return;
		}

		try {
			// Build prompt with skill instructions
			const prompt = `You are a meeting summarization assistant. Analyze the following meeting content and generate a structured summary.

${summarySkill.sections.get('Analysis Points') || ''}

${summarySkill.sections.get('Output Format') || ''}

${summarySkill.sections.get('Style Guidelines') || ''}

Meeting content to summarize:

${contentToSummarize}`;

			// Get summary from Copilot
			const rawSummary = await this.copilotClient.sendPrompt(prompt);

			// Strip any leading heading the AI may have added (e.g. "# Transcript Summary")
			const summary = rawSummary.trim().replace(/^#+ .*\n+/, '').trim();
			
			// Insert or update # Transcript Summary section
			const transcriptSummaryRegex = /# Transcript Summary[\s\S]*?(?=\n# [^#]|$)/;
			let newContent: string;
			
			if (transcriptSummaryRegex.test(content)) {
				newContent = content.replace(transcriptSummaryRegex, `# Transcript Summary\n\n${summary}`);
			} else {
				// Insert before # Transcript if present, otherwise append
				const transcriptRegex = /(# Transcript\s*\n)/;
				if (transcriptRegex.test(content)) {
					newContent = content.replace(transcriptRegex, `# Transcript Summary\n\n${summary}\n\n$1`);
				} else {
					newContent = content + `\n\n# Transcript Summary\n\n${summary}\n`;
				}
			}

			await this.app.vault.modify(file, newContent);
			console.log('Transcript Summary generated and saved');
		} catch (error) {
			console.error('Error generating transcript summary:', error);
			throw error;
		}
	}

	/**
	 * Enhanced summary workflow - generates from transcript and combines with Copilot Summary
	 */
	private async generateEnhancedSummary(file: TFile, content: string): Promise<void> {
		console.log('Generating enhanced summary with both sources...');
		
		try {
			// Step 1: Generate Transcript Summary
			this.statusBar.show('Generating transcript summary...', 0);
			const transcriptSummary = await this.generateTranscriptSummary(content);
			
			if (!transcriptSummary) {
				console.warn('Failed to generate transcript summary, falling back to standard');
				await this.generateStandardSummary(file, content);
				return;
			}

			// Step 2: Combine both summaries
			this.statusBar.show('Combining summaries...', 0);
			const unifiedSummary = await this.combineSummaries(content, transcriptSummary);
			
			if (!unifiedSummary) {
				console.warn('Failed to combine summaries, falling back to standard');
				await this.generateStandardSummary(file, content);
				return;
			}

			// Step 3: Update all sections
			await this.updateSummarySections(file, content, unifiedSummary, transcriptSummary);
			
			console.log('Enhanced summary generated successfully');
		} catch (error) {
			console.error('Error in enhanced summary generation:', error);
			console.log('Falling back to standard summary generation');
			await this.generateStandardSummary(file, content);
		}
	}

	/**
	 * Generate summary from transcript content
	 */
	private async generateTranscriptSummary(content: string): Promise<string | null> {
		console.log('Generating transcript summary...');
		
		// Extract transcript
		const transcriptMatch = content.match(/# Transcript\s*\n([\s\S]*?)(?=\n#|$)/);
		if (!transcriptMatch || !transcriptMatch[1].trim()) {
			console.warn('No transcript content found');
			return null;
		}

		const rawTranscript = transcriptMatch[1].trim();
		console.log('Transcript content length:', rawTranscript.length);
		console.log('Transcript preview:', rawTranscript.substring(0, 200));

		// Resolve any embedded file reference to actual text
		const transcriptContent = await this.resolveTranscriptContent(rawTranscript);
		if (!transcriptContent || transcriptContent.length < 20) {
			console.warn('Could not resolve transcript content or content too short');
			return null;
		}

		try {
			const prompt = `You are analyzing a general meeting transcript. Generate a comprehensive summary with:
- **Key Points**: Main topics discussed
- **Decisions**: Decisions made during the meeting
- **Action Items**: Tasks assigned with owners
- **Follow-up**: Items requiring follow-up

Keep the summary clear, organized, and actionable.

CRITICAL: Do NOT include any markdown headings (# or ##) in your response. Start directly with the content.

Transcript:

${transcriptContent}`;

			const summary = await this.copilotClient.sendPrompt(prompt);
			
			// Strip any headings the AI might have added anyway
			let cleaned = summary.trim();
			cleaned = cleaned.replace(/^#+\s+.*?\n+/gm, ''); // Remove all markdown headings
			
			return cleaned.trim();
		} catch (error) {
			console.error('Error generating transcript summary:', error);
			return null;
		}
	}

	/**
	 * Combine Copilot Summary and Transcript Summary intelligently
	 */
	private async combineSummaries(content: string, transcriptSummary: string): Promise<string | null> {
		console.log('Combining summaries...');
		
		// Extract Copilot Summary (everything until next # heading)
		const copilotMatch = content.match(/# Copilot Summary\s*\n([\s\S]*?)(?=\n#|$)/);
		if (!copilotMatch || !copilotMatch[1].trim()) {
			console.warn('No Copilot Summary content found');
			return transcriptSummary; // Use transcript only
		}

		let copilotSummary = copilotMatch[1].trim();
		console.log('Copilot Summary raw length:', copilotSummary.length);
		console.log('Copilot Summary preview:', copilotSummary.substring(0, 200));

		// Check if we accidentally captured the next heading (empty section)
		if (copilotSummary.startsWith('#')) {
			console.log('Copilot Summary section is empty (captured next heading), using transcript summary only');
			return transcriptSummary;
		}

		// Strip disclaimer text if present (Teams adds this sometimes)
		const disclaimerPatterns = [
			/AI-generated content.*?may be incorrect.*?\[Learn more\]\([^)]+\)/gi,
			/AI-generated content.*?may not be accurate.*?\[Learn more\]\([^)]+\)/gi,
			/This summary was generated by AI.*?may be incorrect.*?\[Learn more\]\([^)]+\]/gi,
			/\[Learn more\]\([^)]+\)/gi
		];
		
		for (const pattern of disclaimerPatterns) {
			copilotSummary = copilotSummary.replace(pattern, '').trim();
		}
		
		console.log('Copilot Summary after disclaimer removal:', copilotSummary.length);
		
		// If nothing left after removing disclaimer, use transcript summary only
		if (copilotSummary.length < 50) {
			console.log('Copilot Summary is empty or too short after disclaimer removal, using transcript summary only');
			return transcriptSummary;
		}

		try {
			const prompt = `You are creating a unified summary for a meeting by combining two sources:

1. **Teams Copilot Summary** (from Microsoft Teams AI):
${copilotSummary}

2. **Transcript Summary** (from meeting transcript):
${transcriptSummary}

Create a single, cohesive summary that:
- Merges duplicate information (don't repeat the same point twice)
- Preserves all unique insights from both sources
- Maintains structured format: Key Points, Decisions, Action Items, Follow-up
- Uses clear, organized bullet points
- Prioritizes accuracy and completeness

CRITICAL: Do NOT include any markdown headings (# or ##) in your response. Start directly with the content.

Generate the unified summary:`;

			const unified = await this.copilotClient.sendPrompt(prompt);
			
			// Strip any headings the AI might have added anyway
			let cleaned = unified.trim();
			cleaned = cleaned.replace(/^#+\s+.*?\n+/gm, ''); // Remove all markdown headings
			
			return cleaned.trim();
		} catch (error) {
			console.error('Error combining summaries:', error);
			return null;
		}
	}

	/**
	 * Update file with all summary sections in correct order
	 */
	private async updateSummarySections(
		file: TFile, 
		content: string, 
		unifiedSummary: string, 
		transcriptSummary: string
	): Promise<void> {
		console.log('Updating summary sections...');
		
		let newContent = content;

		// Insert or update Transcript Summary (above Transcript)
		const transcriptSummarySection = `# Transcript Summary\n\n${transcriptSummary}\n\n`;
		// NOTE: regex must NOT include leading \n in [\s\S]*? or it will swallow the next heading
		// when that heading is the last section (no \n# after it). Instead let [\s\S]*? consume
		// the newline so that (?=\n#) correctly fires before the next top-level heading.
		const transcriptSummaryRegex = /# Transcript Summary[\s\S]*?(?=\n# [^#]|$)/;
		
		if (transcriptSummaryRegex.test(newContent)) {
			// Update existing
			newContent = newContent.replace(transcriptSummaryRegex, transcriptSummarySection.trimEnd());
		} else {
			// Insert before Transcript
			const transcriptRegex = /(# Transcript\s*\n)/;
			if (transcriptRegex.test(newContent)) {
				newContent = newContent.replace(transcriptRegex, transcriptSummarySection + '$1');
			}
		}

		// Insert or update Unified Summary (above Copilot Summary)
		const unifiedSummarySection = `# Unified Summary\n\n${unifiedSummary}\n\n`;
		const unifiedSummaryRegex = /# Unified Summary[\s\S]*?(?=\n# [^#]|$)/;
		
		if (unifiedSummaryRegex.test(newContent)) {
			// Update existing
			newContent = newContent.replace(unifiedSummaryRegex, unifiedSummarySection.trimEnd());
		} else {
			// Insert before Copilot Summary
			const copilotSummaryRegex = /(# Copilot Summary\s*\n)/;
			if (copilotSummaryRegex.test(newContent)) {
				newContent = newContent.replace(copilotSummaryRegex, unifiedSummarySection + '$1');
			}
		}

		await this.app.vault.modify(file, newContent);
		console.log('All summary sections updated');
	}
}
